dataset_path: /data3/gtlim/workspace/src/Video-Oasis/data/benchmarks/videos
dataset_kwargs:
  data_files: {"test" : /data3/gtlim/workspace/src/Video-Oasis/src/lmms_eval/video_oasis.json}
  token: False
  cache_dir: v_oasis
  video: False
task: v_oasis
test_split: test
output_type: generate_until
doc_to_visual: !function utils.v_oasis_doc_to_visual
doc_to_text: !function utils.v_oasis_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 16384
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
process_results: !function utils.v_oasis_process_results
metric_list:
  - metric: v_oasis_perception_score
    aggregation: !function utils.v_oasis_aggregate_results
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "Put your final answer in \\boxed{}."
metadata:
  - version: 0.0
